# Generated by Django 5.2 on 2026-06-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('plataforma', models.SmallIntegerField(choices=[(1, 'PC'), (2, 'PlayStation 4'), (3, 'PlayStation 5'), (4, 'Xbox One'), (5, 'Xbox Series X/S'), (6, 'Nintendo Switch'), (7, 'Mobile')])),
                ('genero', models.SmallIntegerField(choices=[(1, 'Ação'), (2, 'Aventura'), (3, 'RPG'), (4, 'Estratégia'), (5, 'Esporte'), (6, 'Corrida'), (7, 'Simulação'), (8, 'Terror'), (9, 'Puzzle')])),
                ('ano', models.IntegerField()),
                ('desenvolvedor', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jogo/fotos')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
